### ISSUE TITLE
Flind and Steel griefing arena

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#113] opened 2015-05-03 19:23 UTC
If player buy Flint and Steel, he can grief arena.

**Comment by Yannici** [comment] 2015-05-04 07:05
How do they griefing the arena? Does the fire from flint and steel will destroy blocks?

**Comment by Granik24** [comment] 2015-05-04 07:08
Yes, they destroying arena blocks

**Comment by Granik24** [comment] 2015-05-11 19:10
![2015-05-11_21 09 27](https://cloud.githubusercontent.com/assets/4377405/7572913/180887a2-f822-11e4-8c5e-b1c21e7f2aca.png)
Still not solved

**Comment by Yannici** [comment] 2015-05-12 06:03
I'll check that.

**Comment by Yannici** [comment] 2015-05-12 15:44
Tested that, I can't reproduce it. The fire doesn't break any blocks ...

**Comment by Yannici** [comment] 2015-05-12 15:46
Ok, sorry. Fire won't remove so it griefes arena when game is stopped/waiting.

**Comment by Yannici** [comment] 2015-05-12 16:40
Fixed with Version 1.1.4

**Closed by Yannici** 2015-05-12 16:40 UTC
Labels: bug
