### ISSUE TITLE
Errors LOCALE_NOT_FOUND

### ISSUE THREAD

**Issue by helptiger** [Yannici/bedwars-reloaded#90] opened 2015-04-23 09:40 UTC
[11:34:33 INFO]: [BedwarsRel] Enabling BedwarsRel v1.0.14
[11:34:33 INFO]: [Bedwars] Failed to load localization language!
[11:34:33 INFO]: [Bedwars] LOCALE_NOT_FOUND
[11:34:33 INFO]: [Bedwars] LOCALE_NOT_FOUND
[11:34:33 INFO]: [Bedwars] LOCALE_NOT_FOUND

![2015-04-23_11 39 10](https://cloud.githubusercontent.com/assets/10258902/7294415/74bc9aa2-e9ad-11e4-94ba-46db96a5cc45.png)

**Comment by Yannici** [comment] 2015-04-23 10:45
Which locale is set in the config? Do the config files exists?

**Comment by helptiger** [comment] 2015-04-23 10:57
I always use the default configs. If deleted before server restart the default config.yml and the 3 language files are regenerated. So this error makes no sense. Joining impossible!

**Comment by Yannici** [comment] 2015-04-23 11:05
Maybe any read permissions for the files were changed? I can't reproduce that behaviour. The locale files are loading and texts are found, too.

**Comment by Yannici** [comment] 2015-04-24 05:29
Tested on server, should be fixed especially with https://github.com/Yannici/bedwars-reloaded/commit/4c580aa3b65c64763b8ca2acecb6419c4c3365de

**Closed by Yannici** 2015-04-24 05:29 UTC
Labels: no bug
