### ISSUE TITLE
Mysql

### ISSUE THREAD

**Issue by tajem** [Yannici/bedwars-reloaded#417] opened 2016-02-10 13:11 UTC
Hello, i have problem with mysql.
Error:
[14:07:59 INFO]: [BedwarsRel] Enabling BedwarsRel v1.2.8
[14:07:59 INFO]: [BedWars] Initialize database ...
[14:07:59 INFO]: [BedWars] Loading Statistics from Database ...
[14:07:59 WARN]: java.lang.NullPointerException
[14:07:59 WARN]: 	at io.github.yannici.bedwars.Statistics.PlayerStatisticManager.initializeDatabase(Unknown Source)
[14:07:59 WARN]: 	at io.github.yannici.bedwars.Statistics.PlayerStatisticManager.initialize(Unknown Source)
[14:07:59 WARN]: 	at io.github.yannici.bedwars.Main.loadStatistics(Unknown Source)
[14:07:59 WARN]: 	at io.github.yannici.bedwars.Main.onEnable(Unknown Source)
[14:07:59 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[14:07:59 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
[14:07:59 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[14:07:59 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356)
[14:07:59 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316)
[14:07:59 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:418)
[14:07:59 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:382)
[14:07:59 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:337)
[14:07:59 WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:257)
[14:07:59 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528)
[14:07:59 WARN]: 	at java.lang.Thread.run(Thread.java:745)
[14:07:59 INFO]: [BedWars] Done.
[14:07:59 INFO]: [BedWars] Game 'Krolestwo1' successfully loaded!

**Comment by sebastianbinder** [comment] 2016-02-12 07:41
Hi @tajem 
are there any tables for BedwarsRel in your database yet?

**Comment by sebastianbinder** [comment] 2016-02-15 14:40
@tajem - any news on this? If the problem is solved, please close the issue.

**Closed** 2016-02-16 19:13 UTC
Labels: about2close, support
