### ISSUE TITLE
Signs

### ISSUE THREAD

**Issue by Granik24** [Yannici/bedwars-reloaded#50] opened 2015-04-17 14:48 UTC
Hi, can you please add arena names to signs?
http://gyazo.com/f2aa5a97e18f224a11b035934a50e640 - BedWars_1 replace to name of arena. Thanks. 
Also, you can set Spectators to GM 3 (for 1.8)

**Comment by Granik24** [comment] 2015-04-17 15:41
And maybe, this is little buggy
In gama with 0 players? Sorry, no.
http://gyazo.com/2c2bea26445fba0923c5cb50541e18b1

**Comment by Granik24** [comment] 2015-04-17 17:22
I think, it's still buggy. Signs get lags and after that not reloading data.

**Comment by Yannici** [comment] 2015-04-18 10:34
I can't reproduce the sign bugs. Arena name will be added soon.

**Comment by Yannici** [comment] 2015-04-18 20:08
Added and fixed with commit https://github.com/Yannici/bedwars-reloaded/commit/6933d79a12c02203999c07d242eee15360b7a116

**Closed by Yannici** 2015-04-18 20:08 UTC
Labels: bug, request
